version: '3.8'
services:
  db_prod:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'oc_chatop_db'
      MYSQL_USER: 'oc_user'
      MYSQL_PASSWORD: 'oc_pwd'
      MYSQL_ROOT_PASSWORD: 'oc_pwd'
    ports:
      - '3306:3306'
    expose:
      - '3306'